# Generated by Django 4.2.6 on 2023-10-15 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('cod_docente', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_docente', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campi',
            fields=[
                ('id_campi', models.AutoField(primary_key=True, serialize=False)),
                ('cod_campi', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_campi', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_comp', models.AutoField(primary_key=True, serialize=False)),
                ('cod_comp', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_comp', models.CharField(blank=True, max_length=200, null=True)),
                ('sigla_comp', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('cod_curso', models.CharField(blank=True, max_length=200, null=True)),
                ('mat_curso', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_curso', models.CharField(blank=True, max_length=200, null=True)),
                ('turno_curso', models.CharField(blank=True, max_length=200, null=True)),
                ('periodo_curso', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('id_discente', models.AutoField(primary_key=True, serialize=False)),
                ('mat_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('ingresso_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('curso_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('nascimento_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('sexo_discente', models.CharField(blank=True, max_length=200, null=True)),
                ('status_discente', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('cod_nivel', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_nivel', models.CharField(blank=True, max_length=200, null=True)),
                ('sigla_comp', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id_diario', models.AutoField(primary_key=True, serialize=False)),
                ('id_campi', models.ForeignKey(blank=True, db_column='id_campi', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadoc_app.campi')),
                ('id_comp', models.ForeignKey(blank=True, db_column='id_comp', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadoc_app.componente')),
                ('id_curso', models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadoc_app.curso')),
                ('id_discente', models.ForeignKey(blank=True, db_column='id_discente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadoc_app.discente')),
                ('id_docente', models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadoc_app.docente')),
                ('id_nivel', models.ForeignKey(blank=True, db_column='id_nivel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='avadoc_app.nivel')),
            ],
        ),
    ]
