# Generated by Django 4.2.6 on 2023-10-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avadoc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discente',
            name='campus_discente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discente',
            name='desc_curso_discente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discente',
            name='email_discente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discente',
            name='fomr_ing_discente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discente',
            name='mun_res_discente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discente',
            name='naturalidade_discente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discente',
            name='resp_discente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='discente',
            name='tel_discente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
