# Generated by Django 4.2.6 on 2023-10-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avadoc_app', '0002_discente_campus_discente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='mat_curso',
            new_name='turma_curso',
        ),
    ]
