# Generated by Django 4.2.6 on 2023-10-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avadoc_app', '0003_rename_mat_curso_curso_turma_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='cod_comp',
        ),
    ]
