# Generated by Django 4.2.6 on 2023-10-15 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avadoc_app', '0004_remove_componente_cod_comp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='cod_nivel',
        ),
    ]
