# Generated by Django 4.2.6 on 2023-10-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avadoc_app', '0005_remove_nivel_cod_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='sigla_comp',
        ),
    ]
